# Generated by Django 5.2 on 2025-04-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_text_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
    ]
